version: '3.8'
services:

  crud:
    build:
      context: ./crud
      dockerfile: Dockerfile
    env_file:
      - ./crud/.env
    ports:
      - "3001:3000"
    expose:
      - "3002"
    depends_on:
      - db
      - rabbitmq


  campo-update:
    build:
      context: ./campo-update
      dockerfile: Dockerfile
    env_file:
      - ./campo-update/.env
    ports:
      - "3002:3000"
    depends_on:
      - rabbitmq

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: suhtprle
      RABBITMQ_DEFAULT_PASS: j8Cp4FsjEwZM6tP229VggQZBlHjH4UvZ
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db_data: {}